Updated GitHub actions.

diff --git a/.github/workflows/render-readme.yaml b/.github/workflows/render-readme.yaml
--- a/.github/workflows/render-readme.yaml
+++ b/.github/workflows/render-readme.yaml
@@ -1,38 +1,33 @@
-# For help visit following page:
-# https://fromthebottomoftheheap.net/2020/04/30/rendering-your-readme-with-github-actions/
-name: render readme
-
-# Controls when the action will run
+# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
+# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
 on:
   push:
-    branches: master
+    paths: ['README.Rmd']
+
+name: render-rmarkdown
 
 jobs:
-  render:
-    # The type of runner that the job will run on
-    runs-on: macOS-latest
-    
+  render-rmarkdown:
+    runs-on: ubuntu-latest
+    env:
+      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v2
-      - uses: r-lib/actions/setup-r@v1
-      - uses: r-lib/actions/setup-pandoc@v1
-      
-      # Install packages needed
-      - name: install required packages
-        run: Rscript -e 'install.packages(c("devtools", "rmarkdown", "yamlme"), dependencies = TRUE)'
-      
-      # Install packages needed from GitHub
-      - name: install from GitHub
-        run: Rscript -e 'library(devtools);install_github("kamapu/biblio", dependencies = TRUE)'
-        env:
-          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
-      
-      # Render README.md using rmarkdown
-      - name: render README
-        run: Rscript -e 'rmarkdown::render("README.Rmd")'
-      
-      - name: commit rendered README
+      - name: Checkout repo
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - uses: r-lib/actions/setup-pandoc@v2
+
+      - uses: r-lib/actions/setup-r@v2
+
+      - uses: r-lib/actions/setup-renv@v2
+
+      - name: Render Rmarkdown files and Commit Results
         run: |
-          git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
+          RMD_PATH=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '[.]Rmd$'))
+          Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) rmarkdown::render(f)' ${RMD_PATH[*]}
+          git config --local user.name "$GITHUB_ACTOR"
+          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
+          git commit ${RMD_PATH[*]/.Rmd/.md} -m 'Re-build Rmarkdown files' || echo "No changes to commit"
           git push origin || echo "No changes to commit"
